//! Selector-owned ASCII fill masks; no dependency on another mode's textures.
use super::{DIGIT_KEYS, LATIN_KEYS, SYMBOL_KEYS};
use crate::font::RasterizedMenuGlyphSet;
use anyhow::{Result, ensure};
use std::collections::{BTreeMap, BTreeSet};

#[derive(Clone, Debug)]
pub struct SelectorAsciiGlyphs {
    pub bytes: Vec<u8>,
    pub crop: [usize; 4],
    pub mask_stride: usize,
    pub glyph_count: usize,
}

impl SelectorAsciiGlyphs {
    /// 128 byte character-to-slot table (FF means unsupported), followed by
    /// row-major, least-significant-bit-first fill masks. Space has an empty mask.
    /// The caller must reserve the entire blob outside the Hangul pack and its
    /// coordinate table. Outlines must be regenerated by the shared renderer.
    pub fn build(reference: &RasterizedMenuGlyphSet, capacity: usize) -> Result<Self> {
        let required: BTreeSet<_> = LATIN_KEYS
            .chars()
            .chain(DIGIT_KEYS.chars())
            .chain(SYMBOL_KEYS.chars())
            .filter(|&c| c != ' ')
            .collect();
        let mut glyphs = BTreeMap::new();
        // Store only actual ASCII fill bounds. Consumers already union their
        // Hangul/ASCII sprite rectangles; padding that union into every mask
        // wastes space and can destroy useful byte alignment for compression.
        let mut bounds = [20usize, 20, 0, 0];
        for glyph in &reference.glyphs {
            ensure!(
                required.contains(&glyph.character)
                    && glyphs.insert(glyph.character, glyph).is_none()
                    && glyph.pixels.len() == 400
                    && glyph.pixels.iter().all(|p| [0, 3, 13].contains(p)),
                "invalid or duplicate selector ASCII glyph"
            );
            ensure!(glyph.pixels.contains(&13), "blank selector ASCII glyph");
            for (i, &p) in glyph.pixels.iter().enumerate() {
                if p == 13 {
                    bounds[0] = bounds[0].min(i % 20);
                    bounds[1] = bounds[1].min(i / 20);
                    bounds[2] = bounds[2].max(i % 20 + 1);
                    bounds[3] = bounds[3].max(i / 20 + 1);
                }
            }
        }
        ensure!(
            glyphs.keys().copied().collect::<BTreeSet<_>>() == required,
            "selector ASCII repertoire is incomplete"
        );
        let [x, y, right, bottom] = bounds;
        ensure!(
            x > 0 && y > 0 && right < 20 && bottom < 20,
            "selector ASCII lacks room for its outline"
        );
        let crop = [x, y, right - x, bottom - y];
        let mask_stride = (crop[2] * crop[3]).div_ceil(8);
        let length = 128 + mask_stride * (glyphs.len() + 1);
        ensure!(
            length <= capacity,
            "selector ASCII masks exceed reserved storage"
        );
        let mut bytes = vec![0; length];
        bytes[..128].fill(255);
        bytes[usize::from(b' ')] = 0;
        for (index, (&character, glyph)) in glyphs.iter().enumerate() {
            let slot = index + 1;
            bytes[character as usize] = u8::try_from(slot)?;
            for row in 0..crop[3] {
                for col in 0..crop[2] {
                    if glyph.pixels[(y + row) * 20 + x + col] == 13 {
                        let bit = row * crop[2] + col;
                        bytes[128 + slot * mask_stride + bit / 8] |= 1 << (bit % 8);
                    }
                }
            }
        }
        Ok(Self {
            bytes,
            crop,
            mask_stride,
            glyph_count: glyphs.len() + 1,
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::font::rasterize_menu_glyphs;

    #[test]
    #[ignore = "requires fonts in ../fonts/"]
    fn all_keyboard_ascii_masks_preserve_fill_and_fit_beside_the_current_pack() {
        let path =
            std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../fonts/galmuri/Galmuri11.ttf");
        let mut reference = rasterize_menu_glyphs(
            &path,
            &format!("{LATIN_KEYS}{DIGIT_KEYS}{SYMBOL_KEYS}").replace(' ', ""),
            12.0,
            3,
            13,
        )
        .unwrap();
        let pack = SelectorAsciiGlyphs::build(&reference, 18800 - 16940).unwrap();
        for glyph in &reference.glyphs {
            let slot = usize::from(pack.bytes[glyph.character as usize]);
            assert!(slot < pack.glyph_count);
            let [x, y, w, h] = pack.crop;
            for row in 0..20 {
                for col in 0..20 {
                    let fill = if (x..x + w).contains(&col) && (y..y + h).contains(&row) {
                        let bit = (row - y) * w + col - x;
                        pack.bytes[128 + slot * pack.mask_stride + bit / 8] & (1 << (bit % 8)) != 0
                    } else {
                        false
                    };
                    assert_eq!(
                        fill,
                        glyph.pixels[row * 20 + col] == 13,
                        "{} ({col},{row})",
                        glyph.character
                    );
                }
            }
        }
        assert_eq!(pack.bytes[usize::from(b' ')], 0);
        assert!(
            pack.bytes[128..128 + pack.mask_stride]
                .iter()
                .all(|&b| b == 0)
        );
        for code in 0..128 {
            assert_eq!(
                pack.bytes[code] != 255,
                code == usize::from(b' ')
                    || reference
                        .glyphs
                        .iter()
                        .any(|g| g.character as usize == code)
            );
        }
        assert!(SelectorAsciiGlyphs::build(&reference, pack.bytes.len() - 1).is_err());
        reference.glyphs.pop();
        assert!(SelectorAsciiGlyphs::build(&reference, 1860).is_err());
    }
}
